spring.datasource.platform: "mysql"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://127.0.0.1:3306/restbuffer"
spring.datasource.username: "root"
spring.datasource.password: "Test_1234"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect:
     "org.hibernate.dialect.MySQL5Dialect"
spring:
  jpa:
    hibernate:
      ddl-auto: update
